version: "3.8"
services:
  db:
    container_name: wagtail_blog_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wagtail_blog_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: wagtail_blog_ppgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"