# Generated by Django 5.0.9 on 2024-09-12 06:55

import blocks.blocks
import wagtail.blocks
import wagtail.blocks.static_block
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('image', blocks.blocks.ImageBlock(group='media')), ('doc', wagtail.documents.blocks.DocumentChooserBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('call_to_action_1', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('page', wagtail.blocks.PageChooserBlock()), ('button_text', wagtail.blocks.CharBlock(max_length=100, required=False))])), ('corousel', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('quotation', wagtail.blocks.StreamBlock([('text', wagtail.blocks.TextBlock()), ('author', wagtail.blocks.CharBlock())]))])), ('info', wagtail.blocks.static_block.StaticBlock(admin_text='ini namanya static blocks')), ('faq', blocks.blocks.FAQListBlock()), ('paragraph', blocks.blocks.ParagraphBlock())], blank=True, null=True),
        ),
    ]
